#!/bin/sh
### BEGIN INIT INFO
# Provides: Rational Team Concert Build System
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 5
# Short-Description:
# Description:
### END INIT INFO
timestamp=`date '+%Y%M%d-%H%m%S'`

REPO_URL="https://sma-unleash.ratl.swg.usma.ibm.com:9445/rtc"
USERID="swilbur@us.ibm.com"
ENGINE_ID="sma-unleashvm01_engine0"
PASS_FILENAME="swilbur.rtcpass"
WORK_DIR=/var/ibm/jbe
JBE_INSTALL_LOCATION=/opt/IBM/CLM401/TeamConcertBuild/

JAVA_HOME=${JBE_INSTALL_LOCATION}/jdk
JBE_EXEC=${JBE_INSTALL_LOCATION}/bin/jbe
LOGFILE=${WORK_DIR}/logs/jbe-${ENGINE_ID}.out
PASSFILE=${WORK_DIR}/${PASS_FILENAME}

case "$1" in
'start')
  echo "Starting the Jazz Build Engine"
  if [ -e ${LOGFILE} ]
  then
  mv ${LOGFILE} ${LOGFILE}.${timestamp}
  fi
  echo "Starting jbe process. stdout/stderr redirected to ${LOGFILE}"
  cd ${WORK_DIR}/${ENGINE_ID}
  nohup ${JBE_EXEC} -repository ${REPO_URL} -engineId ${ENGINE_ID} -userId ${USERID} -passwordFile ${PASSFILE} >${LOGFILE} 2>&1 &
  ;;

'stop')
  echo "Killing jbe processes:" $(ps -C jbe -o pid=)
  ps -C jbe -o pid= | xargs kill
  ;;

'restart')
  $0 stop
  sleep 5
  $0 start
  ;;

*)
  echo "Usage: $0 { start | stop | restart }"
  ;;

esac

exit 0
